type: paradedb
mode: standalone
version:
  major: "18"
  paradedb: "0.21.7"
cluster:
  instances: 1
backups:
  enabled: false
imageCatalog:
  create: true
  images:
    - major: 18
      image: my-custom-postgres-image:mytag
