{{- $alert := "CNPGClusterLogicalReplicationApplyErrors" -}}
{{- if not (has $alert .excludeRules) -}}
alert: {{ $alert }}
annotations:
  summary: ParadeDB CNPG Cluster logical replication apply errors detected
  description: |-
    ParadeDB CloudNativePG Cluster's "{{ .namespace }}/{{ .cluster }}" "{{ "{{ .subname }}" }}" subscription has experienced {{ .value }} apply errors in the last 5 minutes.

    Apply errors occur when the subscriber cannot apply changes from the publisher, which can lead to data inconsistency if not addressed.
  runbook_url: https://github.com/paradedb/charts/blob/main/charts/paradedb/docs/runbooks/{{ $alert }}.md
expr: |
  label_replace(increase(max by (namespace, job, subname) (cnpg_pg_stat_subscription_apply_error_count)[5m]), "cluster", "$1", "job", ".+/(.+)") > 0
for: 2m
labels:
  severity: warning
  namespace: {{ .namespace }}
  cnpg_cluster: {{ .cluster }}
{{- end -}}