{{- $alert := "CNPGClusterLogicalReplicationHighErrorRate" -}}
{{- if not (has $alert .excludeRules) -}}
alert: {{ $alert }}
annotations:
  summary: ParadeDB CNPG Cluster high logical replication error rate
  description: |-
    ParadeDB CloudNativePG Cluster's "{{ .namespace }}/{{ .cluster }}" "{{ "{{ .subname }}" }}" subscription has a high error rate of {{ .value }} errors/minute over the last 10 minutes.

    Sustained error rates indicate persistent replication problems that may affect data consistency and require investigation.
  runbook_url: https://github.com/paradedb/charts/blob/main/charts/paradedb/docs/runbooks/{{ $alert }}.md
expr: |
  label_replace(rate(max by (namespace, job, subname) (cnpg_pg_stat_subscription_apply_error_count + cnpg_pg_stat_subscription_sync_error_count)[10m:1m]) * 60, "cluster", "$1", "job", ".+/(.+)") > 0.5
for: 5m
labels:
  severity: warning
  namespace: {{ .namespace }}
  cnpg_cluster: {{ .cluster }}
{{- end -}}